#!/usr/bin/env python3

# Importing libraries
# For using my GPU I have to do that...
# export TF_MIN_GPU_MULTIPROCESSOR_COUNT=2

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys
sys.path.insert(0, './lib')

import pdb
import os
from timer import Timer
from timer import timestring
import json
from argparse import ArgumentParser

# PARSING COMMAND LINE ARGUMENTS
cmd = ArgumentParser(prog="caes-bin",
                     description="Stacked Convolutional Autoencoder",
                     epilog="Matteo Ragni, David Windridge - 2016")

DEFAULT_TRAINING_DIR  = '/tmp/training_nn'
CURRENT_TRAINING_TIME = timestring()
DEFAULT_RUNNING_DIR   = os.path.join(DEFAULT_TRAINING_DIR, CURRENT_TRAINING_TIME + '-run')
DEFAULT_SAVING_DIR    = os.path.join(DEFAULT_TRAINING_DIR, 'save-' + CURRENT_TRAINING_TIME + '-cae.ckpt')
DEFAULT_BATCH_SIZE    = 10
DEFAULT_STEP_SIZE     = 10
DEFAULT_LEARN_RATE    = 0.01
VERBOSITY             = 1
BATCH_LIMIT           = 4

# TODO: Modify run and training dir to add a single
# voice to define the path, and another to define the run.

cmd.add_argument('-in', dest='dataset', type=str, nargs=1, required=True,
                 help='Input dataset for the training')
cmd.add_argument('-gpu', dest='gpu', action='store_true',
                 help='Enable CUDA and CuDNN [NO]')
cmd.add_argument('-r', '--run', dest='runs', type=str, nargs=1, default=DEFAULT_RUNNING_DIR,
                 help='Define a specific run directory [%s]' % DEFAULT_RUNNING_DIR)
cmd.add_argument('-s', '--save', dest='save', type=str, nargs=1, default=DEFAULT_SAVING_DIR,
                 help='NOT IMPLEMENTED - Define save positions for the result of the training, as checkpoint [%s]' % DEFAULT_SAVING_DIR)
cmd.add_argument('-bs', '--batchsize', dest='batchsize', type=int, nargs=1, default=DEFAULT_BATCH_SIZE,
                 help='Define the size of each batch. It must be compatible with RAM or VRAM capabilities. It must be positive [%d]' % DEFAULT_BATCH_SIZE)
cmd.add_argument('-ss', '--stepsize', dest='stepsize', type=int, nargs=1, default=DEFAULT_STEP_SIZE,
                 help='Define the number of step optimizer will run on each batch. It must be positive [%d]' % DEFAULT_STEP_SIZE)
cmd.add_argument('-lr', '--learnrate', dest='learnrate', type=float, nargs=1, default=DEFAULT_LEARN_RATE,
                 help='Define the learning rate for the optimizer [%f]' % DEFAULT_LEARN_RATE)
cmd.add_argument('-v', '--verbosity', dest='verb', type=int, nargs=1, default=VERBOSITY,
                 help='Define verbosity level, from 0 to 3 [%d]' % VERBOSITY)
cmd.add_argument('-rl', '--residual-learning', dest='residuals', action='store_true',
                 help='Enable residual learning (NO -> y = f(g(x)), YES -> y = f(g(x)) + x) [NO]')
cmd.add_argument('-tg', '--telegram', dest='telegram', action='store_true',
                 help='Enable notifications using system telegram bot [NO]')
cmd_args = cmd.parse_args()

# Handles the command line arguments and check everything is ok
try:
    assert os.path.isfile(' '.join(cmd_args.dataset)), "Dataset file [%s] does not exist" % ' '.join(cmd_args.dataset)
    assert cmd_args.stepsize  > 0,                     "Step size must be a positive integer"
    assert cmd_args.batchsize > 0,                     "Batch size must be a positive integer"
    assert cmd_args.learnrate  > 0.0,                   "Batch size must be a positive float"
except AssertionError as error:
    print("Input Error10: " + str(error))
    exit(126)

if cmd_args.verb > 3:
    VERBOSITY = 3
elif cmd_args.verb < 0:
    VERBOSITY = 0

def batch_loop(length):
    VERBOSITY = cmd_args.verb[0]

# DEVICE_PLACEMENT_LOG = True if VERBOSITY > 1 else False
DEVICE_PLACEMENT_LOG = False

# Telegram notifications
if cmd_args.telegram:
    from tg_notifier import TelegramNotifier
    notifier = TelegramNotifier()
    def notify(m):
        notifier.post(m)
else:
    def notify(m):
        pass

# Logging function
def log(s, l=1):
    if l >= VERBOSITY:
        print(s)
    if l == 1:
        notify(str(s))

# MAIN PART
from six.moves import cPickle as pickle
import numpy as np
import tensorflow as tf
import autoencoder


# Some definitions on the engine
FLAGS = tf.app.flags.FLAGS
tf.app.flags.DEFINE_string('dataset_file',
                           cmd_args.dataset[0],
                           "Dataset file for training")
tf.app.flags.DEFINE_string('train_dir',
                           cmd_args.runs,
                           "Training directory")
tf.app.flags.DEFINE_string('saver_dir',
                           cmd_args.save,
                           "Chackpoint file for saving")
tf.app.flags.DEFINE_integer('max_steps',
                            cmd_args.stepsize,
                            "Number of steps for the optimizer on each batch")
tf.app.flags.DEFINE_integer('batch_size',
                            cmd_args.stepsize,
                            "Number of elements in each batch")
tf.app.flags.DEFINE_boolean('log_device_placement',
                            DEVICE_PLACEMENT_LOG,
                            "Logging of the use of my device")
tf.app.flags.DEFINE_boolean('gpu_enabled',
                            cmd_args.gpu,
                            "Enables the use of GPU for Convolutions")
tf.app.flags.DEFINE_float('learning_rate',
                          cmd_args.learnrate,
                          "Optimizer learning rate")

# Define configurations for the Convolutional Autoencoder
# To get a preview of the options that can be set, print(sets)
sets1 = autoencoder.ConvAutoEncSettings()
sets1.prefix_name = "alpha"
sets1.input_shape = [FLAGS.batch_size, 193, 193, 1]
sets1.corruption = False
sets1.layers = 2
sets1.patch_size = 3
sets1.strides = [1, 2, 2, 1]
sets1.padding = 'SAME'
sets1.depth_increasing = 1
sets1.residual_learning = cmd_args.residuals

sets2 = autoencoder.ConvAutoEncSettings()
sets2.prefix_name = "beta"
sets2.input_shape = [FLAGS.batch_size, 49, 49, 4]
sets2.corruption = False
sets2.layers = 1
sets2.patch_size = 3
sets2.strides = [1, 2, 2, 1]
sets2.padding = 'SAME'
sets2.depth_increasing = 1
sets2.residual_learning = cmd_args.residuals

sets3 = autoencoder.ConvAutoEncSettings()
sets3.prefix_name = "gamma"
sets3.input_shape = [FLAGS.batch_size, 25, 25, 6]
sets3.corruption = False
sets3.layers = 1
sets3.patch_size = 5
sets3.strides = [1, 2, 2, 1]
sets3.padding = 'SAME'
sets3.depth_increasing = 1
sets3.residual_learning = cmd_args.residuals

sets = (sets1, sets2, sets3)

def batch_loop(length):
    for i in range(0, length//FLAGS.batch_size):
        init = i * FLAGS.batch_size
        ends = (i + 1) * FLAGS.batch_size
        yield(init, ends)

# Check if there is a checkpoint to restore
RESTORE = os.path.isfile(FLAGS.saver_dir)

# Loading the Convolutional Autoencoder
stack = autoencoder.ConvAutoEncStack(sets)

merged = tf.merge_all_summaries()
writer = tf.train.SummaryWriter(FLAGS.train_dir, stack.graph)
counter = 0

# try:
for session, n, cae, x in stack.trainBlocks():
    with open(FLAGS.dataset_file, "rb") as f:
        no_batch = pickle.load(f)
        assert type(no_batch) is int, "First reading must be an int (number of batches)"
        BATCH_LIMIT = no_batch if BATCH_LIMIT > no_batch else BATCH_LIMIT
        result = [None, 99999999.9999999]
        with tf.name_scope("TRAINING-%d" % n):
            for b in range(0, BATCH_LIMIT):
                log("RUNNING BATCH: %d (c: %i, e: %5.10f)" % (b, counter, result[1]))
                dataset = pickle.load(f)
                for init, ends in batch_loop(np.shape(dataset)[0]):
                    with Timer(): # batch timing
                        for step in range(0, FLAGS.max_steps):
                            result = session.run([cae.optimizer], feed_dict={x: dataset[init:ends, :, :, :]})
                            counter += 1
                        result = session.run([merged, cae.error], feed_dict={x: dataset[init:ends, :, :, :]})
                        log("Error at step %i is: %5.10f" % (counter, result[1]), 2)
                        writer.add_summary(result[0], counter)
# finally:
#   stack.close()
log("Learning Completed")
notify("Learning completed")
exit(0)
