#!/usr/bin/env python3

# Importing libraries
# For using my GPU I have to do that...
# export TF_MIN_GPU_MULTIPROCESSOR_COUNT=2

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys
sys.path.insert(0, './lib')

import os
from timer import Timer
import timer

from data_handler import DataHandler
from autoenc_shell import ConvAutoEncShell
import tensorflow as tf
from autoenc_shell import *




cmd = ConvAutoEncArgParse()


# from autoenc_shell import ConvAutoEncShell
ConvAutoEncShell(cmd)

exit(0)
